{{- if .Values.deploy -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "parsec.name" . }}-pricing-cache
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
    component: api
spec:
  {{- if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end -}}
