{{- if and .Values.deploy .Values.oauth.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: oauth-proxy-service
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
    component: oauth-proxy
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: oauth-serving-cert
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: {{ include "parsec.name" . }}-oauth-proxy
    component: oauth-proxy
{{- end -}}
