{{- if and .Values.deploy .Values.oauth.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "parsec.serviceAccountName" . }}
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
    component: oauth
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: |
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "parsec.name" . }}-route"}}
automountServiceAccountToken: true
{{- end -}}
