{{- if and .Values.deploy .Values.secrets.aap2 -}}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ include "parsec.name" . }}-aap2-credentials
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    {{- range $cluster, $bitwardenSecret := .Values.secrets.aap2 }}
    PARSEC_AAP2__CLUSTERS__{{ $cluster | upper }}__URL:
      secret: {{ $bitwardenSecret }}
      key: url
    PARSEC_AAP2__CLUSTERS__{{ $cluster | upper }}__USERNAME:
      secret: {{ $bitwardenSecret }}
      key: username
    PARSEC_AAP2__CLUSTERS__{{ $cluster | upper }}__PASSWORD:
      secret: {{ $bitwardenSecret }}
      key: password
    {{- end }}
{{- end -}}
