{{- if .Values.deploy -}}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ include "parsec.name" . }}-cloud-credentials
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    PARSEC_AWS__ACCESS_KEY_ID:
      secret: {{ .Values.secrets.cloudCredentials.aws }}
      key: access_key_id
    PARSEC_AWS__SECRET_ACCESS_KEY:
      secret: {{ .Values.secrets.cloudCredentials.aws }}
      key: secret_access_key
    PARSEC_AZURE__CLIENT_ID:
      secret: {{ .Values.secrets.cloudCredentials.azure }}
      key: client_id
    PARSEC_AZURE__CLIENT_SECRET:
      secret: {{ .Values.secrets.cloudCredentials.azure }}
      key: client_secret
    PARSEC_AZURE__TENANT_ID:
      secret: {{ .Values.secrets.cloudCredentials.azure }}
      key: tenant_id
    PARSEC_AZURE__STORAGE_ACCOUNT:
      secret: {{ .Values.secrets.cloudCredentials.azure }}
      key: storage_account
    PARSEC_AZURE__CONTAINER:
      secret: {{ .Values.secrets.cloudCredentials.azure }}
      key: container
    PARSEC_GCP__PROJECT_ID:
      secret: {{ .Values.secrets.cloudCredentials.gcp }}
      key: project_id
    PARSEC_GCP__BILLING_DATASET:
      secret: {{ .Values.secrets.cloudCredentials.gcp }}
      key: billing_dataset
    PARSEC_GCP__BILLING_ACCOUNT_ID:
      secret: {{ .Values.secrets.cloudCredentials.gcp }}
      key: billing_account_id
{{- end -}}
