{{- if and .Values.deploy .Values.secrets.kubeconfigs.babylon -}}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: babylon-kubeconfigs
  namespace: {{ include "parsec.namespaceName" . }}
  labels:
    {{- include "parsec.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    {{- range $cluster, $bitwardenSecret := .Values.secrets.kubeconfigs.babylon }}
    {{ $cluster }}.kubeconfig:
      secret: {{ $bitwardenSecret }}
    {{- end }}
{{- end -}}
