apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parsec-oauth-prod
  labels:
    app: parsec
    component: oauth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parsec-oauth
subjects:
  - kind: ServiceAccount
    name: parsec-oauth
    namespace: parsec
