apiVersion: batch/v1
kind: CronJob
metadata:
  name: parsec-azure-billing-refresh
spec:
  schedule: "0 4 * * *"  # Daily at 04:00 UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 14400  # 4 hour timeout
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: parsec
            component: azure-billing-refresh
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: refresh
              image: parsec:latest
              command: ["python3", "scripts/refresh_azure_billing.py"]
              envFrom:
                - secretRef:
                    name: parsec-cloud-credentials
              volumeMounts:
                - name: pricing-cache
                  mountPath: /app/data
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          volumes:
            - name: pricing-cache
              persistentVolumeClaim:
                claimName: parsec-pricing-cache
          restartPolicy: OnFailure
