{{- if and .Values.deploy .Values.api.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-api-htpasswd
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: api-proxy
  annotations:
    secret-generator.v1.mittwald.de/type: "basic-auth"
    secret-generator.v1.mittwald.de/basic-auth-username: {{ .Values.api.username | quote }}
type: Opaque
data: {}
{{- end -}}
