{{- if and .Values.deploy .Values.api.enabled -}}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: mlflow-api-htpasswd
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: api-proxy
spec:
  forceRegenerate: false
  data:
    username: {{ .Values.api.username | quote }}
  fields:
    - fieldName: htpasswd
      encoding: "base64"
      length: "32"
{{- end -}}
