{{- if and .Values.deploy .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mlflow-api-proxy
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: api-proxy
spec:
  type: ClusterIP
  selector:
    app: mlflow
    component: api-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
{{- end -}}
