{{- if and .Values.deploy .Values.oauth.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-oauth
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: oauth
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: |
      {
        "kind": "OAuthRedirectReference",
        "apiVersion": "v1",
        "reference": {
          "kind": "Route",
          "name": "mlflow-route"
        }
      }
{{- end -}}
