{{- if .Values.deploy -}}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: mlflow-postgres
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: postgres
spec:
  forceRegenerate: false
  data:
    database-name: {{ .Values.postgres.database | quote }}
    database-user: {{ .Values.postgres.username | quote }}
  fields:
    - fieldName: database-password
      encoding: "hex"
      length: "32"
{{- end -}}
