{{- if .Values.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres
  namespace: {{ include "mlflow.namespaceName" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mlflow
      component: postgres
  template:
    metadata:
      labels:
        app: mlflow
        component: postgres
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgresql
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: 5432
              name: postgresql
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres
                  key: database-name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-postgres
                  key: database-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          livenessProbe:
            exec:
              command:
                - /usr/bin/pg_isready
                - -U
                - $(POSTGRESQL_USER)
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /usr/bin/pg_isready
                - -U
                - $(POSTGRESQL_USER)
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: mlflow-postgres-data
{{- end -}}
