"""Tool: query_aws_pricing — look up on-demand pricing for AWS instance types.

Reads from a static pricing cache (data/ec2_pricing.json) generated by
scripts/refresh_pricing.py. No AWS credentials required at runtime.
"""

import json
import logging
import os

logger = logging.getLogger(__name__)

_pricing_data: dict | None = None
_pricing_mtime: float = 0.0
_PRICING_FILE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "data",
    "ec2_pricing.json",
)


def _load_pricing() -> dict:
    """Load pricing data from the static cache file.

    Checks file mtime on each call (cheap stat) and reloads automatically
    when the CronJob writes a newer file to the PVC.
    """
    global _pricing_data, _pricing_mtime

    try:
        current_mtime = os.path.getmtime(_PRICING_FILE)
    except OSError:
        if _pricing_data is not None:
            return _pricing_data
        raise FileNotFoundError(f"Pricing cache not found: {_PRICING_FILE}")

    if _pricing_data is None or current_mtime > _pricing_mtime:
        with open(_PRICING_FILE) as f:
            data = json.load(f)
        _pricing_data = data
        _pricing_mtime = current_mtime
        count = data.get("instance_count", 0)
        generated = data.get("generated_at", "unknown")
        logger.info(
            "Loaded EC2 pricing cache: %d instance types (generated %s)",
            count,
            generated,
        )

    assert _pricing_data is not None
    return _pricing_data


async def query_aws_pricing(
    instance_type: str,
    region: str = "us-east-1",
    os_type: str = "Linux",
) -> dict:
    """Look up on-demand pricing for an AWS EC2 instance type.

    Args:
        instance_type: EC2 instance type (e.g. g4dn.xlarge, m5.large).
        region: AWS region code (e.g. us-east-1). Default: us-east-1.
        os_type: Operating system. Default: Linux.

    Returns:
        Dict with pricing details.
    """
    try:
        data = _load_pricing()
    except FileNotFoundError:
        return {"error": "Pricing cache not found. Run: python3 scripts/refresh_pricing.py"}

    instances = data.get("instances", {})
    instance = instances.get(instance_type)

    if not instance:
        return {
            "instance_type": instance_type,
            "region": region,
            "error": (
                f"No pricing data for {instance_type}. "
                "Instance type may not exist or cache may need refreshing."
            ),
        }

    region_pricing = instance.get("pricing", {}).get(region, {})
    hourly_price = region_pricing.get(os_type)

    if hourly_price is None:
        available_regions = list(instance.get("pricing", {}).keys())
        return {
            "instance_type": instance_type,
            "region": region,
            "error": (
                f"No {os_type} pricing for {instance_type} in {region}. "
                f"Available regions: {', '.join(sorted(available_regions)[:5])}"
            ),
        }

    return {
        "instance_type": instance_type,
        "region": region,
        "pricing": {
            "instance_type": instance_type,
            "vcpu": instance.get("vcpu", ""),
            "memory": instance.get("memory", ""),
            "gpu": instance.get("gpu", ""),
            "gpu_memory": instance.get("gpu_memory", ""),
            "storage": instance.get("storage", ""),
            "network": instance.get("network", ""),
            "hourly_price_usd": hourly_price,
            "daily_price_usd": round(hourly_price * 24, 2),
            "monthly_price_usd": round(hourly_price * 730, 2),
            "os": os_type,
            "region": region,
        },
    }
